import os
import re

source_file = r"e:\Users\xiongaox\Downloads\Orbis\notes\buchuiniu\full copy.md"
output_base = r"e:\Users\xiongaox\Downloads\Orbis\notes\buchuiniu"

def sanitize_filename(name):
    return re.sub(r'[\\/*?:"<>|]', "", name).strip()


def main():
    if not os.path.exists(source_file):
        print(f"Source file not found: {source_file}")
        return

    # cleanup previous run (optional, or just do it blindly for subdirs that differ from source file)
    # listing all dirs
    for item in os.listdir(output_base):
        item_path = os.path.join(output_base, item)
        if os.path.isdir(item_path):
            # We assume all subdirs are generated by us or should be cleaned up to start fresh
            # But let's be careful. strictly speaking we should only remove what we created.
            # But since the folder contained only the file before, it's likely safe.
            # to be safe, only remove if it contains words like "实例", "例题" or matches our categories.
            try:
                import shutil
                shutil.rmtree(item_path)
                print(f"Removed old dir: {item}")
            except Exception as e:
                print(f"Failed to remove {item}: {e}")

    with open(source_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    current_category = None
    current_title = None
    current_content = []
    
    # Regex to capture the category and title
    header_pattern = re.compile(r'^#\s*(.*?)(?:---|—|----)(.*)$')

    for line in lines:
        match = header_pattern.match(line)
        if match:
            if current_category and current_title:
                save_case(current_category, current_title, current_content)
                current_content = []

            raw_cat = match.group(1).strip()
            raw_title = match.group(2).strip()

            # Normalize Category
            # Check if category ends with 实例X, 例题X, etc.
            # Regex to separate the real category from the instance number
            # Common patterns: "工作与求职类实例十六", "求职与工作类"
            # We want to extract "工作与求职类" and move "实例十六" to title if present.
            
            sub_match = re.search(r'^(.*?)((?:实例|例题|例)[0-9一二三四五六七八九十]*)$', raw_cat)
            if sub_match:
                current_category = sub_match.group(1).strip()
                suffix = sub_match.group(2).strip()
                current_title = f"{suffix}：{raw_title}"
            else:
                current_category = raw_cat
                current_title = raw_title
            
            # Additional cleanup for dashes in title start
            current_title = current_title.lstrip('-').lstrip('—').strip()
            
            # Remove dashes/separators that appear after the colon
            # e.g. "例题一：—Title" -> "例题一：Title"
            current_title = re.sub(r'([：:])\s*[-—]+', r'\1', current_title)
            
            # Also clean up multiple colons if any "例题：: Title"
            current_title = re.sub(r'[：:]+', '：', current_title)

            current_content.append(line)
        else:
            if current_category and current_title:
                current_content.append(line)

    if current_category and current_title:
        save_case(current_category, current_title, current_content)


def save_case(category, title, content):
    # Sanitize names
    safe_category = sanitize_filename(category)
    safe_title = sanitize_filename(title)
    
    if not safe_category or not safe_title:
        print(f"Skipping invalid entry: {category} - {title}")
        return

    # Create directory
    category_dir = os.path.join(output_base, safe_category)
    if not os.path.exists(category_dir):
        os.makedirs(category_dir)
        print(f"Created directory: {category_dir}")

    # Write file
    file_path = os.path.join(category_dir, f"{safe_title}.md")
    with open(file_path, 'w', encoding='utf-8') as f:
        f.writelines(content)
    print(f"Saved: {file_path}")

if __name__ == "__main__":
    main()
