/**
 * @deprecated 此文件已废弃，请使用 src/lib/xuan-bazi 库代替。
 * 保留此文件仅供参考和向后兼容，新代码请勿引用。
 * 
 * 术数通用工具库 (Metaphysics Shared Utilities)
 * 包含：天干、地支、五行、纳音、神煞、十二长生等通用定义
 */

// --- 基础常量定义 (Basic Constants) ---

export const TIAN_GAN = ['甲', '乙', '丙', '丁', '戊', '己', '庚', '辛', '壬', '癸'];
export const DI_ZHI = ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥'];

// 五行映射 (Elements Map)
export const GAN_ELEMENT_MAP: Record<string, string> = {
    '甲': 'wood', '乙': 'wood', '丙': 'fire', '丁': 'fire', '戊': 'earth',
    '己': 'earth', '庚': 'metal', '辛': 'metal', '壬': 'water', '癸': 'water'
};

export const ZHI_ELEMENT_MAP: Record<string, string> = {
    '子': 'water', '丑': 'earth', '寅': 'wood', '卯': 'wood', '辰': 'earth',
    '巳': 'fire', '午': 'fire', '未': 'earth', '申': 'metal', '酉': 'metal',
    '戌': 'earth', '亥': 'water'
};

// 五行颜色定义 (Element Colors)
export const ELEMENT_COLORS: Record<string, string> = {
    wood: '#22c55e',
    fire: '#ef4444',
    earth: '#CD853F',
    metal: '#d4af37',
    water: '#3b82f6'
};

// 综合元数据 (Element Metadata)
export const ELEMENT_META: Record<string, { element: string; polarity: 'yang' | 'yin' }> = {
    // 天干
    '甲': { element: 'wood', polarity: 'yang' },
    '乙': { element: 'wood', polarity: 'yin' },
    '丙': { element: 'fire', polarity: 'yang' },
    '丁': { element: 'fire', polarity: 'yin' },
    '戊': { element: 'earth', polarity: 'yang' },
    '己': { element: 'earth', polarity: 'yin' },
    '庚': { element: 'metal', polarity: 'yang' },
    '辛': { element: 'metal', polarity: 'yin' },
    '壬': { element: 'water', polarity: 'yang' },
    '癸': { element: 'water', polarity: 'yin' },
    // 地支
    '子': { element: 'water', polarity: 'yang' },
    '丑': { element: 'earth', polarity: 'yin' },
    '寅': { element: 'wood', polarity: 'yang' },
    '卯': { element: 'wood', polarity: 'yin' },
    '辰': { element: 'earth', polarity: 'yang' },
    '巳': { element: 'fire', polarity: 'yin' },
    '午': { element: 'fire', polarity: 'yang' },
    '未': { element: 'earth', polarity: 'yin' },
    '申': { element: 'metal', polarity: 'yang' },
    '酉': { element: 'metal', polarity: 'yin' },
    '戌': { element: 'earth', polarity: 'yang' },
    '亥': { element: 'water', polarity: 'yin' }
};

// --- 八字相关映射 (Bazi Specific Maps) ---

// 十神表 (Shi Shen Map) - 日主 -> 天干 -> 十神
export const SHI_SHEN_MAP: Record<string, Record<string, string>> = {
    '甲': { '甲': '比肩', '乙': '劫财', '丙': '食神', '丁': '伤官', '戊': '偏财', '己': '正财', '庚': '七杀', '辛': '正官', '壬': '偏印', '癸': '正印' },
    '乙': { '甲': '劫财', '乙': '比肩', '丙': '伤官', '丁': '食神', '戊': '正财', '己': '偏财', '庚': '正官', '辛': '七杀', '壬': '正印', '癸': '偏印' },
    '丙': { '甲': '偏印', '乙': '正印', '丙': '比肩', '丁': '劫财', '戊': '食神', '己': '伤官', '庚': '偏财', '辛': '正财', '壬': '七杀', '癸': '正官' },
    '丁': { '甲': '正印', '乙': '偏印', '丙': '劫财', '丁': '比肩', '戊': '伤官', '己': '食神', '庚': '正财', '辛': '偏财', '壬': '正官', '癸': '七杀' },
    '戊': { '甲': '七杀', '乙': '正官', '丙': '偏印', '丁': '正印', '戊': '比肩', '己': '劫财', '庚': '食神', '辛': '伤官', '壬': '偏财', '癸': '正财' },
    '己': { '甲': '正官', '乙': '七杀', '丙': '正印', '丁': '偏印', '戊': '劫财', '己': '比肩', '庚': '伤官', '辛': '食神', '壬': '正财', '癸': '偏财' },
    '庚': { '甲': '偏财', '乙': '正财', '丙': '七杀', '丁': '正官', '戊': '偏印', '己': '正印', '庚': '比肩', '辛': '劫财', '壬': '食神', '癸': '伤官' },
    '辛': { '甲': '正财', '乙': '偏财', '丙': '正官', '丁': '七杀', '戊': '正印', '己': '偏印', '庚': '劫财', '辛': '比肩', '壬': '伤官', '癸': '食神' },
    '壬': { '甲': '食神', '乙': '伤官', '丙': '偏财', '丁': '正财', '戊': '七杀', '己': '正官', '庚': '偏印', '辛': '正印', '壬': '比肩', '癸': '劫财' },
    '癸': { '甲': '伤官', '乙': '食神', '丙': '正财', '丁': '偏财', '戊': '正官', '己': '七杀', '庚': '正印', '辛': '偏印', '壬': '劫财', '癸': '比肩' },
};

// 十神缩写 (Shi Shen Abbreviations)
export const SHI_SHEN_ABBR: Record<string, string> = {
    '比肩': '比',
    '劫财': '劫',
    '食神': '食',
    '伤官': '伤',
    '正财': '财',
    '偏财': '才',
    '正印': '印',
    '偏印': '枭',
    '正官': '官',
    '七杀': '杀',
};

// 五行相生 (Element Generation Cycle)
export const ELEMENT_GENERATES: Record<string, string> = {
    wood: 'fire',
    fire: 'earth',
    earth: 'metal',
    metal: 'water',
    water: 'wood',
};

// 五行相克 (Element Control Cycle)
export const ELEMENT_CONTROLS: Record<string, string> = {
    wood: 'earth',
    earth: 'water',
    water: 'fire',
    fire: 'metal',
    metal: 'wood',
};

// 五行被生 (Element Generated By)
export const ELEMENT_GENERATED_BY: Record<string, string> = {
    fire: 'wood',
    earth: 'fire',
    metal: 'earth',
    water: 'metal',
    wood: 'water',
};

// 五行被克 (Element Controlled By)
export const ELEMENT_CONTROLLED_BY: Record<string, string> = {
    earth: 'wood',
    water: 'earth',
    fire: 'water',
    metal: 'fire',
    wood: 'metal',
};
// 地支本气映射 (Main Hidden Stem for each Branch)
export const ZHI_BEN_QI: Record<string, string> = {
    '子': '癸', '丑': '己', '寅': '甲', '卯': '乙',
    '辰': '戊', '巳': '丙', '午': '丁', '未': '己',
    '申': '庚', '酉': '辛', '戌': '戊', '亥': '壬',
};

/**
 * 根据日主和目标干支计算十神
 * 对于地支，使用其本气天干来计算
 * @param dayMaster 日主天干
 * @param target 目标天干或地支
 * @returns 十神全称
 */
export function getShiShen(dayMaster: string, target: string): string {
    // 如果是地支，先转换为本气天干
    const actualTarget = ZHI_BEN_QI[target] || target;

    const day = ELEMENT_META[dayMaster];
    const meta = ELEMENT_META[actualTarget];
    if (!day || !meta) return '';

    const samePolarity = day.polarity === meta.polarity;
    if (meta.element === day.element) {
        return samePolarity ? '比肩' : '劫财';
    }
    if (meta.element === ELEMENT_GENERATES[day.element]) {
        return samePolarity ? '食神' : '伤官';
    }
    if (meta.element === ELEMENT_CONTROLS[day.element]) {
        return samePolarity ? '偏财' : '正财';
    }
    if (meta.element === ELEMENT_GENERATED_BY[day.element]) {
        return samePolarity ? '偏印' : '正印';
    }
    if (meta.element === ELEMENT_CONTROLLED_BY[day.element]) {
        return samePolarity ? '七杀' : '正官';
    }
    return '';
}

/**
 * 获取十神缩写
 * @param dayMaster 日主天干
 * @param target 目标天干或地支
 * @returns 十神缩写（单字）
 */
export function getShiShenAbbr(dayMaster: string, target: string): string {
    return SHI_SHEN_ABBR[getShiShen(dayMaster, target)] ?? '';
}

// 地支藏干 (Zang Gan / Hidden Stems)
export const ZANG_GAN_MAP: Record<string, string[]> = {
    '子': ['癸'], '丑': ['己', '癸', '辛'], '寅': ['甲', '丙', '戊'], '卯': ['乙'],
    '辰': ['戊', '乙', '癸'], '巳': ['丙', '庚', '戊'], '午': ['丁', '己'], '未': ['己', '丁', '乙'],
    '申': ['庚', '壬', '戊'], '酉': ['辛'], '戌': ['戊', '辛', '丁'], '亥': ['壬', '甲'],
};

// 纳音 (Na Yin)
export const NA_YIN_MAP: Record<string, string> = {
    '甲子': '海中金', '乙丑': '海中金', '丙寅': '炉中火', '丁卯': '炉中火', '戊辰': '大林木', '己巳': '大林木', '庚午': '路旁土', '辛未': '路旁土', '壬申': '剑锋金', '癸酉': '剑锋金',
    '甲戌': '山头火', '乙亥': '山头火', '丙子': '涧下水', '丁丑': '涧下水', '戊寅': '城头土', '己卯': '城头土', '庚辰': '白蜡金', '辛巳': '白蜡金', '壬午': '杨柳木', '癸未': '杨柳木',
    '甲申': '泉中水', '乙酉': '泉中水', '丙戌': '屋上土', '丁亥': '屋上土', '戊子': '霹雳火', '己丑': '霹雳火', '庚寅': '松柏木', '辛卯': '松柏木', '壬辰': '长流水', '癸巳': '长流水',
    '甲午': '砂中金', '乙未': '砂中金', '丙申': '山下火', '丁酉': '山下火', '戊戌': '平地木', '己亥': '平地木', '庚子': '壁上土', '辛丑': '壁上土', '壬寅': '金箔金', '癸卯': '金箔金',
    '甲辰': '覆灯火', '乙巳': '覆灯火', '丙午': '天河水', '丁未': '天河水', '戊申': '大驿土', '己酉': '大驿土', '庚戌': '钗钏金', '辛亥': '钗钏金', '壬子': '桑柘木', '癸丑': '桑柘木',
    '甲寅': '大溪水', '乙卯': '大溪水', '丙辰': '沙中土', '丁巳': '沙中土', '戊午': '天上火', '己未': '天上火', '庚申': '石榴木', '辛酉': '石榴木', '壬戌': '大海水', '癸亥': '大海水',
};

// 十二长生 (12 Life Stages / Chang Sheng)
export const CHANG_SHENG_MAP: Record<string, Record<string, string>> = {
    '甲': { '亥': '长生', '子': '沐浴', '丑': '冠带', '寅': '临官', '卯': '帝旺', '辰': '衰', '巳': '病', '午': '死', '未': '墓', '申': '绝', '酉': '胎', '戌': '养' },
    '乙': { '午': '长生', '巳': '沐浴', '辰': '冠带', '卯': '临官', '寅': '帝旺', '丑': '衰', '子': '病', '亥': '死', '戌': '墓', '酉': '绝', '申': '胎', '未': '养' },
    '丙': { '寅': '长生', '卯': '沐浴', '辰': '冠带', '巳': '临官', '午': '帝旺', '未': '衰', '申': '病', '酉': '死', '戌': '墓', '亥': '绝', '子': '胎', '丑': '养' },
    '丁': { '酉': '长生', '申': '沐浴', '未': '冠带', '午': '临官', '巳': '帝旺', '辰': '衰', '卯': '病', '寅': '死', '丑': '墓', '子': '绝', '亥': '胎', '戌': '养' },
    '戊': { '寅': '长生', '卯': '沐浴', '辰': '冠带', '巳': '临官', '午': '帝旺', '未': '衰', '申': '病', '酉': '死', '戌': '墓', '亥': '绝', '子': '胎', '丑': '养' },
    '己': { '酉': '长生', '申': '沐浴', '未': '冠带', '午': '临官', '巳': '帝旺', '辰': '衰', '卯': '病', '寅': '死', '丑': '墓', '子': '绝', '亥': '胎', '戌': '养' },
    '庚': { '巳': '长生', '午': '沐浴', '未': '冠带', '申': '临官', '酉': '帝旺', '戌': '衰', '亥': '病', '子': '死', '丑': '墓', '寅': '绝', '卯': '胎', '辰': '养' },
    '辛': { '子': '长生', '亥': '沐浴', '戌': '冠带', '酉': '临官', '申': '帝旺', '未': '衰', '午': '病', '巳': '死', '辰': '墓', '卯': '绝', '寅': '胎', '丑': '养' },
    '壬': { '申': '长生', '酉': '沐浴', '戌': '冠带', '亥': '临官', '子': '帝旺', '丑': '衰', '寅': '病', '卯': '死', '辰': '墓', '巳': '绝', '午': '胎', '未': '养' },
    '癸': { '卯': '长生', '寅': '沐浴', '丑': '冠带', '子': '临官', '亥': '帝旺', '戌': '衰', '酉': '病', '申': '死', '未': '墓', '午': '绝', '巳': '胎', '辰': '养' },
};

// --- 辅助函数 (Helper Functions) ---

/**
 * 获取天干或地支的五行
 * @param char 天干或地支字符
 * @returns 'wood' | 'fire' | 'earth' | 'metal' | 'water' | ''
 */
export function getElement(char: string): string {
    return GAN_ELEMENT_MAP[char] || ZHI_ELEMENT_MAP[char] || '';
}

/**
 * 获取五行对应的颜色
 * @param char 天干或地支字符
 * @returns Hex Color String
 */
export function getElementColor(char: string): string {
    const element = getElement(char);
    return ELEMENT_COLORS[element] || 'currentColor';
}

/**
 * 计算旬空 (Xun Kong / Void)
 * @param ganZhi 干支字符串 (如 "甲子")
 * @returns 旬空字符串 (如 "戌亥")
 */
export function getXunKong(ganZhi: string): string {
    if (!ganZhi || ganZhi.length < 2) return '';
    const gan = ganZhi[0];
    const zhi = ganZhi[1];

    const ganList = TIAN_GAN;
    const zhiList = DI_ZHI;

    const ganIdx = ganList.indexOf(gan) + 1;
    const zhiIdx = zhiList.indexOf(zhi) + 1;

    let diff = ganIdx - zhiIdx;
    if (diff <= 0) diff += 12;

    const lookup: Record<number, string> = {
        12: '戌亥', 10: '子丑', 8: '寅卯', 6: '辰巳', 4: '午未', 2: '申酉'
    };
    return lookup[diff] || '';
}

// --- 神煞表 (Shen Sha Tables) ---

export const TIAN_YI_MAP: Record<string, string[]> = {
    '甲': ['丑', '未'], '戊': ['丑', '未'], '庚': ['丑', '未'],
    '乙': ['子', '申'], '己': ['子', '申'],
    '丙': ['亥', '酉'], '丁': ['亥', '酉'],
    '壬': ['巳', '卯'], '癸': ['巳', '卯'],
    '辛': ['午', '寅']
};

export const TAI_JI_MAP: Record<string, string[]> = {
    '甲': ['子', '午'], '乙': ['子', '午'],
    '丙': ['酉', '卯'], '丁': ['酉', '卯'],
    '戊': ['辰', '戌', '丑', '未'], '己': ['辰', '戌', '丑', '未'],
    '庚': ['寅', '亥'], '辛': ['寅', '亥'],
    '壬': ['巳', '申'], '癸': ['巳', '申']
};

export const YI_MA_MAP: Record<string, string> = {
    '申': '寅', '子': '寅', '辰': '寅',
    '寅': '申', '午': '申', '戌': '申',
    '巳': '亥', '酉': '亥', '丑': '亥',
    '亥': '巳', '卯': '巳', '未': '巳'
};

export const TAO_HUA_MAP: Record<string, string> = {
    '申': '酉', '子': '酉', '辰': '酉',
    '寅': '卯', '午': '卯', '戌': '卯',
    '巳': '午', '酉': '午', '丑': '午',
    '亥': '子', '卯': '子', '未': '子'
};

export const WEN_CHANG_MAP: Record<string, string> = {
    '甲': '巳', '乙': '午',
    '丙': '申', '戊': '申',
    '丁': '酉', '己': '酉',
    '庚': '亥', '辛': '子',
    '壬': '寅', '癸': '卯'
};

/**
 * 获取基础神煞 (Basic Shen Sha Calculation)
 * @param dayGan 日干
 * @param dayZhi 日支
 * @param yearZhi 年支
 * @param zhiSet 全局地支集合
 */
export function getBasicShenSha(dayGan: string, dayZhi: string, yearZhi: string, zhiSet: Set<string>): string[] {
    const stars: Set<string> = new Set();

    const hasZhi = (targets: string | string[]) => {
        const arr = Array.isArray(targets) ? targets : [targets];
        return arr.some(z => zhiSet.has(z));
    };

    if (hasZhi(TIAN_YI_MAP[dayGan] || [])) stars.add('天乙贵人');
    if (hasZhi(TAI_JI_MAP[dayGan] || [])) stars.add('太极贵人');
    if (hasZhi(WEN_CHANG_MAP[dayGan] || [])) stars.add('文昌贵人');
    if (hasZhi(YI_MA_MAP[dayZhi] || '') || hasZhi(YI_MA_MAP[yearZhi] || '')) stars.add('驿马');
    if (hasZhi(TAO_HUA_MAP[dayZhi] || '') || hasZhi(TAO_HUA_MAP[yearZhi] || '')) stars.add('桃花');

    return Array.from(stars);
}
